#!/usr/bin/python3
import threading
liste = ["4", "12", "34", "128", "1024", "4958", "1718944270642558716715","9","99","999","9999","9797973","49","239809320265259"]


def factoring(liste, start, end):
    while(start < end):
        temp = int(liste[start])
        j = 2
        while(j <= int(temp / 2)):
            if(temp % j == 0):
                ch = str(temp) + "=" + str(int(temp /
 j)) + "*" + str(j)
                liste[start] = ch
                break
            j += 1
        start += 1


t1 = threading.Thread(target=factoring, args=(liste, 0, int(len(liste)/2),))
t2 = threading.Thread(target=factoring, args=(liste, int(len(liste)/2)+1, len(liste),))
t1.start()
t2.start()
print(liste)
