#!/usr/python3
import sys
import os.path
if(len(sys.argv) == 2):
    if(os.path.isfile(sys.argv[1])):
        with open(sys.argv[1]) as f:
            for line in f:
                print(int(line))
    else:
        print("Please check file path")
else:
    print("Please set file path")
