#!/usr/bin/python3
liste = ["12", "4", "6", "8","9"]


def factoring(liste, start, end):
    while(start < end):
        temp = int(liste[start])
        j = 2
        while(j <= int(temp / 2)):
            if(temp % j == 0):
                ch = str(temp) + "=" + str(int(temp /
 j)) + "*" + str(j)
                print(ch)
                break
            j += 1
        start += 1


factoring(liste, 0, 5)
print(liste)
