#!/usr/python3
import sys
import os.path
import time
if(len(sys.argv) == 2):
    if(os.path.isfile(sys.argv[1])):
        cutime=time.time()*1000
        with open(sys.argv[1]) as f:
            for line in f:
                toint = int(line)
                for i in range(2, int(toint/2)+1):
                    if(toint % i == 0):
                        print("{}={}*{}".format(toint,int(toint / i),i))
                        break
        print("exec time",(time.time()*1000)-cutime)
    else:
        print("Please check file path")
elif(len(sys.argv) == 1):
    print("Please set file path")
else:
    print("Please set only one argument")
